"""
tests/test_harness_rundb_corpus.py

Loads the shared run_db.sqlite fixture corpus (runnerd/harness/testdata/rundb,
generated by scripts/gen_rundb_fixtures.py from src.run_db's real schema) and
checks the Python side agrees with the Go journal validator
(runnerd/nashnet/quarantine/rundbcheck.go) on every fixture's accept/reject
verdict (cambia-1717, design v1.1-compute-pool-design.md D55/D61).

Scope note: the reconciler's `replay()` (src/harness/reconciler.py) does not
yet enforce D55's schema-subset, single-row, or identity checks -- `_read_runs`
currently replays every row in a pulled `runs` table with no name filter, so a
second row or a wrong-name row passes through `replay()` unrejected today.
Wiring that enforcement into `replay()` is a separate ticket (W1-T9, D61); this
test therefore exercises a standalone reference validator, `_validate_journal`
below, built the same way the Go validator is (independently, from the design)
rather than a passthrough over reconciler internals -- except where a real
reconciler primitive already exists, which it reuses rather than re-deriving:
`reconciler._ALLOWED_STATUS` for the enum check. Once W1-T9 lands full D55
enforcement in `replay()` itself, this file's job is to be pointed at that
instead of `_validate_journal`; the corpus and expected verdicts do not change.
"""

import json
import sqlite3
from pathlib import Path
from typing import Dict, Set, Tuple

import pytest

from src.harness.reconciler import _ALLOWED_STATUS
from src.run_db import _DDL

_REPO_ROOT = Path(__file__).resolve().parents[2]
_CORPUS_DIR = _REPO_ROOT / "runnerd" / "harness" / "testdata" / "rundb"

_DEFAULT_MAX_BYTES = 256 * 1024 * 1024
_DEFAULT_MAX_ROWS_PER_TABLE = 200000

# Reason codes mirror rundbcheck.go's Reason* constants (kept as plain string
# literals since Go constants cannot be imported here; drift between the two
# lists is exactly what running both suites against the same corpus catches).
REASON_SIZE_CAP = "size_cap"
REASON_INTEGRITY_CHECK = "integrity_check"
REASON_SCHEMA = "schema"
REASON_IDENTITY = "identity"
REASON_ENUM = "enum"
REASON_ROW_COUNT = "row_count"


def _reference_schema() -> Dict[str, Set[str]]:
    """Build the known {table: {columns}} map from src.run_db's own _DDL by
    executing it against a scratch in-memory db and introspecting the result,
    rather than hand-copying a second schema literal. This is the Python
    side's anti-drift mechanism, matching the corpus generator's own approach
    (build fixtures through the real schema, never a copy of it)."""
    conn = sqlite3.connect(":memory:")
    try:
        conn.executescript(_DDL)
        tables: Dict[str, Set[str]] = {}
        for (name,) in conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table'"
        ).fetchall():
            if name.startswith("sqlite_"):
                continue
            cols = {row[1] for row in conn.execute(f"PRAGMA table_info({name})")}
            tables[name] = cols
        return tables
    finally:
        conn.close()


_REFERENCE_SCHEMA = _reference_schema()


def _validate_journal(
    path: Path,
    expected_name: str,
    max_bytes: int = _DEFAULT_MAX_BYTES,
    max_rows_per_table: int = _DEFAULT_MAX_ROWS_PER_TABLE,
) -> Tuple[bool, str]:
    """Reference D55 validator: size cap, read-only immutable open,
    integrity_check, schema subset (against _REFERENCE_SCHEMA), single-row
    identity, enum (against the real reconciler._ALLOWED_STATUS), row-count
    caps. Returns (accepted, reason); reason is "" when accepted.

    Mirrors rundbcheck.go's Validate check-by-check so the two independent
    implementations can be run against the same corpus and compared.
    """
    if not path.exists():
        raise FileNotFoundError(path)
    if path.stat().st_size > max_bytes:
        return False, REASON_SIZE_CAP

    uri = f"file:{path}?mode=ro&immutable=1"
    try:
        conn = sqlite3.connect(uri, uri=True)
    except sqlite3.DatabaseError:
        return False, REASON_INTEGRITY_CHECK
    try:
        try:
            rows = conn.execute("PRAGMA integrity_check").fetchall()
        except sqlite3.DatabaseError:
            return False, REASON_INTEGRITY_CHECK
        if len(rows) != 1 or rows[0][0] != "ok":
            return False, REASON_INTEGRITY_CHECK

        present: Set[str] = set()
        for (name,) in conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table'"
        ).fetchall():
            if name == "sqlite_sequence" or name.startswith("sqlite_"):
                continue
            if name not in _REFERENCE_SCHEMA:
                return False, REASON_SCHEMA
            present.add(name)
            cols = {row[1] for row in conn.execute(f"PRAGMA table_info({name})")}
            if not cols.issubset(_REFERENCE_SCHEMA[name]):
                return False, REASON_SCHEMA

        if "runs" not in present:
            return False, REASON_SCHEMA

        (count,) = conn.execute("SELECT COUNT(*) FROM runs").fetchone()
        if count != 1:
            return False, REASON_IDENTITY
        name, status = conn.execute("SELECT name, status FROM runs").fetchone()
        if name != expected_name:
            return False, REASON_IDENTITY
        if status not in _ALLOWED_STATUS:
            return False, REASON_ENUM

        for table in (
            "config_snapshots",
            "checkpoints",
            "eval_results",
            "head_to_head",
            "harness_sync",
            "harness_reflection",
        ):
            if table not in present:
                continue
            (n,) = conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()
            if n > max_rows_per_table:
                return False, REASON_ROW_COUNT

        return True, ""
    finally:
        conn.close()


def _load_manifest() -> list:
    manifest_path = _CORPUS_DIR / "manifest.json"
    with open(manifest_path) as f:
        return json.load(f)["fixtures"]


def _checked_in_fixtures():
    for fx in _load_manifest():
        if fx["file"] is not None:
            yield fx


@pytest.mark.parametrize(
    "fixture", list(_checked_in_fixtures()), ids=lambda fx: fx["file"]
)
def test_fixture_corpus_agrees_on_verdict(fixture):
    """AC (2): the Python side loads the same corpus as the Go validator and
    agrees on accept/reject for every checked-in fixture."""
    path = _CORPUS_DIR / fixture["file"]
    accepted, reason = _validate_journal(path, fixture["expected_name"])
    want_accept = fixture["verdict"] == "accept"
    assert accepted == want_accept, (
        f"{fixture['file']}: got accepted={accepted} reason={reason!r}, "
        f"want accepted={want_accept}"
    )
    if not want_accept:
        assert reason == fixture["reason"], (
            f"{fixture['file']}: rejected with reason {reason!r}, "
            f"want {fixture['reason']!r}"
        )


def test_oversized_fixture_rejected(tmp_path):
    """The size_cap fixture is generated at test time (manifest lists it with
    file: null) rather than checked in, matching the Go suite's approach."""
    path = tmp_path / "oversized.sqlite"
    max_bytes = 4096
    with open(path, "wb") as f:
        f.truncate(max_bytes * 2)
    accepted, reason = _validate_journal(path, "job-train-0001", max_bytes=max_bytes)
    assert not accepted
    assert reason == REASON_SIZE_CAP


def test_manifest_covers_all_named_fixture_kinds():
    """Sanity check on the corpus itself: every fixture kind the ticket names
    is present, so a missing fixture fails loudly here instead of the
    parametrized test silently running with fewer cases."""
    fixtures = _load_manifest()
    reasons_seen = {fx["reason"] for fx in fixtures if fx["verdict"] == "reject"}
    assert reasons_seen == {
        REASON_SIZE_CAP,
        REASON_INTEGRITY_CHECK,
        REASON_SCHEMA,
        REASON_IDENTITY,
        REASON_ENUM,
    }
    accept_count = sum(1 for fx in fixtures if fx["verdict"] == "accept")
    assert accept_count == 2  # valid train, valid evaluate
