package quarantine

import (
	"encoding/json"
	"go/build"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"
)

// testdataDir is runnerd/harness/testdata/rundb relative to this package
// (runnerd/nashnet/quarantine), the corpus shared with the Python reconciler
// suite (D55/D61) and generated by cfr/scripts/gen_rundb_fixtures.py from
// cfr/src/run_db.py's real schema.
const testdataDir = "../../harness/testdata/rundb"

type fixtureEntry struct {
	File         *string `json:"file"`
	Kind         string  `json:"kind"`
	ExpectedName string  `json:"expected_name"`
	Verdict      string  `json:"verdict"`
	Reason       string  `json:"reason"`
}

type fixtureManifest struct {
	Fixtures []fixtureEntry `json:"fixtures"`
}

func loadManifest(t *testing.T) fixtureManifest {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(testdataDir, "manifest.json"))
	if err != nil {
		t.Fatalf("reading manifest.json: %v", err)
	}
	var m fixtureManifest
	if err := json.Unmarshal(data, &m); err != nil {
		t.Fatalf("parsing manifest.json: %v", err)
	}
	if len(m.Fixtures) == 0 {
		t.Fatal("manifest.json lists no fixtures")
	}
	return m
}

// TestFixtureCorpus is AC (1): each checked-in fixture yields its named
// verdict. The size_cap fixture (file: null) is covered separately by
// TestOversizedFixtureRejected, since it is synthesized at test time rather
// than checked in.
func TestFixtureCorpus(t *testing.T) {
	manifest := loadManifest(t)
	checked := 0
	for _, fx := range manifest.Fixtures {
		fx := fx
		if fx.File == nil {
			continue
		}
		t.Run(*fx.File, func(t *testing.T) {
			path := filepath.Join(testdataDir, *fx.File)
			v, err := Validate(path, fx.ExpectedName)
			if err != nil {
				t.Fatalf("Validate(%s): unexpected error: %v", path, err)
			}
			wantAccept := fx.Verdict == "accept"
			if v.Accepted != wantAccept {
				t.Fatalf("Validate(%s) = Accepted=%v Reason=%q Detail=%q, want Accepted=%v",
					path, v.Accepted, v.Reason, v.Detail, wantAccept)
			}
			if !wantAccept && v.Reason != fx.Reason {
				t.Fatalf("Validate(%s) rejected with reason %q, want %q (detail: %s)",
					path, v.Reason, fx.Reason, v.Detail)
			}
		})
		checked++
	}
	if checked == 0 {
		t.Fatal("no checked-in fixtures were exercised: the corpus loader is checking nothing")
	}
}

// TestOversizedFixtureRejected is the size_cap half of AC (1). The oversized
// fixture is not checked in (manifest.json lists it with file: null): a
// sparse file past the cap is synthesized here so the test stays fast and
// the repository does not carry a large binary blob.
func TestOversizedFixtureRejected(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "oversized.sqlite")
	f, err := os.Create(path)
	if err != nil {
		t.Fatalf("creating oversized fixture: %v", err)
	}
	const maxBytes = 4096
	if err := f.Truncate(maxBytes * 2); err != nil {
		f.Close()
		t.Fatalf("truncating oversized fixture: %v", err)
	}
	if err := f.Close(); err != nil {
		t.Fatalf("closing oversized fixture: %v", err)
	}

	v, err := ValidateWithConfig(path, "job-train-0001", RunDBConfig{MaxBytes: maxBytes})
	if err != nil {
		t.Fatalf("ValidateWithConfig: unexpected error: %v", err)
	}
	if v.Accepted {
		t.Fatal("oversized fixture was accepted, want rejected")
	}
	if v.Reason != ReasonSizeCap {
		t.Fatalf("oversized fixture rejected with reason %q, want %q", v.Reason, ReasonSizeCap)
	}
}

// TestValidatorNeverWrites is AC (3): Validate must never mutate the file it
// checks. Asserted two ways: the file's mtime is unchanged across a call
// (functional evidence), and the source opens with the immutable=1 URI
// parameter (structural evidence, read from the file this test accompanies
// so it fails if that literal is ever edited out).
func TestValidatorNeverWrites(t *testing.T) {
	manifest := loadManifest(t)
	var fixturePath string
	var expectedName string
	for _, fx := range manifest.Fixtures {
		if fx.File != nil && fx.Verdict == "accept" {
			fixturePath = filepath.Join(testdataDir, *fx.File)
			expectedName = fx.ExpectedName
			break
		}
	}
	if fixturePath == "" {
		t.Fatal("manifest has no accept-verdict fixture to check mtime against")
	}

	before, err := os.Stat(fixturePath)
	if err != nil {
		t.Fatalf("stat before Validate: %v", err)
	}

	if _, err := Validate(fixturePath, expectedName); err != nil {
		t.Fatalf("Validate: unexpected error: %v", err)
	}

	after, err := os.Stat(fixturePath)
	if err != nil {
		t.Fatalf("stat after Validate: %v", err)
	}
	if !before.ModTime().Equal(after.ModTime()) {
		t.Fatalf("mtime changed across Validate: before=%v after=%v", before.ModTime(), after.ModTime())
	}
	if before.Size() != after.Size() {
		t.Fatalf("size changed across Validate: before=%d after=%d", before.Size(), after.Size())
	}

	src, err := os.ReadFile("rundbcheck.go")
	if err != nil {
		t.Fatalf("reading rundbcheck.go: %v", err)
	}
	if !strings.Contains(string(src), "mode=ro&immutable=1") {
		t.Fatal("rundbcheck.go no longer opens with mode=ro&immutable=1")
	}
}

// TestValidatorLeafImports is AC (4): rundbcheck.go links only the sqlite
// driver and the Go standard library. Parsed via go/parser rather than a
// build-graph tool, so the check has no dependency beyond the toolchain
// already required to build the module.
func TestValidatorLeafImports(t *testing.T) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "rundbcheck.go", nil, parser.ImportsOnly)
	if err != nil {
		t.Fatalf("parsing rundbcheck.go: %v", err)
	}
	if len(f.Imports) == 0 {
		t.Fatal("rundbcheck.go has no imports: the leaf-package check is asserting nothing")
	}
	for _, imp := range f.Imports {
		path, err := strconv.Unquote(imp.Path.Value)
		if err != nil {
			t.Fatalf("unquoting import path %s: %v", imp.Path.Value, err)
		}
		if path == "modernc.org/sqlite" {
			continue
		}
		pkg, err := build.Import(path, ".", build.FindOnly)
		if err != nil {
			t.Fatalf("resolving import %q: %v", path, err)
		}
		if !pkg.Goroot {
			t.Errorf("rundbcheck.go imports %q, which is neither the sqlite driver nor a standard-library package", path)
		}
	}
}

// TestQueryTimeoutDefault is a narrow sanity check that the exported default
// constants line up with the design's stated values (D55), so a future edit
// that silently drops the cap is caught here rather than only in the corpus.
func TestQueryTimeoutDefault(t *testing.T) {
	if DefaultQueryTimeout != 5*time.Second {
		t.Fatalf("DefaultQueryTimeout = %v, want 5s", DefaultQueryTimeout)
	}
	if DefaultMaxRunDBBytes != 256*1024*1024 {
		t.Fatalf("DefaultMaxRunDBBytes = %d, want 256 MiB", DefaultMaxRunDBBytes)
	}
}
