package main

import (
	"bytes"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/jason-s-yu/cambia/runnerd/nodeagent"
	"gopkg.in/yaml.v3"
)

// nodeInitBanner is the comment header written above the generated nashnet:
// section. It carries no per-node values, so it needs no template
// substitution and can never itself break the file's YAML.
const nodeInitBanner = `# nashnet node config, generated by ` + "`cambia-runnerd node init`" + ` (design D25).
#
# This file's only secret-adjacent value is key_path, which names the file
# holding the node's own ed25519 private key (0600, generated alongside this
# file, never transmitted). Nothing here needs an ssh key: a node enrolls
# through an operator-minted grant (design D60), not ssh access, and
# runnerd/README.md's node enrollment section walks through the rest: mint
# the grant against this node's public key with "cambia harness node grant",
# drop it onto the coordinator's nodes directory over your own admin path,
# then start this node with:
#   cambia-runnerd --role node --node-config <this file>
#
# Edit slots, kinds, and labels below to taste; every other field already
# validates against the coordinator this was generated for.

`

// runNodeSubcommand dispatches `cambia-runnerd node <verb>`. This is
// distinct from --role node, which runs the node agent itself: this tree is
// offline operator tooling, currently just init (design D25).
func runNodeSubcommand(args []string) {
	if len(args) == 0 {
		fmt.Fprintln(os.Stderr, "usage: cambia-runnerd node init [flags]")
		os.Exit(2)
	}
	switch args[0] {
	case "init":
		runNodeInit(args[1:])
	default:
		fmt.Fprintf(os.Stderr, "cambia-runnerd node: unknown verb %q (want: init)\n", args[0])
		os.Exit(2)
	}
}

// buildNodeConfigFile assembles the nodeagent.File that node init writes,
// given the key just generated/loaded and the operator's flags. Split out of
// runNodeInit so node_init_test.go exercises the exact struct the CLI
// writes, not a hand-copied stand-in.
func buildNodeConfigFile(nodeID, coordinatorURL, fingerprint, keyPath, baseDir, runsDir string, slots int, labels []string) nodeagent.File {
	return nodeagent.File{
		Nashnet: nodeagent.Config{
			NodeID: nodeID,
			Coordinator: nodeagent.Coordinator{
				URL:        coordinatorURL,
				CertSHA256: fingerprint,
			},
			KeyPath: keyPath,
			BaseDir: baseDir,
			RunsDir: runsDir,
			Slots:   slots,
			Labels:  labels,
		},
	}
}

// marshalNodeConfigFile renders f as yaml, 2-space indented to match the
// rest of the repo's yaml config files.
func marshalNodeConfigFile(f nodeagent.File) ([]byte, error) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(f); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// runNodeInit is `cambia-runnerd node init`: generate this node's ed25519
// key (0600, local only, design D25) and write a nashnet: config template an
// operator fills in and points --role node at.
func runNodeInit(args []string) {
	fs := flag.NewFlagSet("node init", flag.ExitOnError)
	coordinatorURL := fs.String("coordinator-url", "",
		"coordinator's https:// URL (required)")
	fingerprint := fs.String("coordinator-fingerprint", "",
		"coordinator's leaf certificate SHA256 fingerprint, 64 hex chars "+
			"(required; openssl x509 -in <cert> -noout -fingerprint -sha256)")
	configPath := fs.String("config", "./nashnet-node.yaml",
		"path to write the node config template")
	keyPath := fs.String("key-path", "",
		"path for the node's ed25519 private key (default <base-dir>/nashnet-node.key)")
	baseDir := fs.String("base-dir", "/srv/cambia",
		"node base directory for ingest caches and staging")
	runsDir := fs.String("runs-dir", "",
		"node run directory (default <base-dir>/runs)")
	slots := fs.Int("slots", 1,
		"declared concurrency slots (clamped by the enrollment grant, D47)")
	labelsFlag := fs.String("labels", "",
		"comma-separated operator labels, matched against a job's requires.labels_any")
	force := fs.Bool("force", false, "overwrite an existing file at --config")
	if err := fs.Parse(args); err != nil {
		log.Fatalf("node init: %v", err)
	}

	if strings.TrimSpace(*coordinatorURL) == "" || strings.TrimSpace(*fingerprint) == "" {
		log.Fatal("node init: --coordinator-url and --coordinator-fingerprint are required")
	}
	if _, err := os.Stat(*configPath); err == nil && !*force {
		log.Fatalf("node init: %s already exists (use --force to overwrite)", *configPath)
	}

	kp := *keyPath
	if kp == "" {
		kp = filepath.Join(*baseDir, "nashnet-node.key")
	}
	priv, created, err := nodeagent.LoadOrCreateKey(kp)
	if err != nil {
		log.Fatalf("node init: key: %v", err)
	}
	signer, err := nodeagent.NewSigner(priv, nil)
	if err != nil {
		log.Fatalf("node init: key: %v", err)
	}

	var labels []string
	for _, l := range strings.Split(*labelsFlag, ",") {
		if l = strings.TrimSpace(l); l != "" {
			labels = append(labels, l)
		}
	}

	file := buildNodeConfigFile(signer.NodeID(), *coordinatorURL, *fingerprint, kp, *baseDir, *runsDir, *slots, labels)
	body, err := marshalNodeConfigFile(file)
	if err != nil {
		log.Fatalf("node init: render config: %v", err)
	}
	out := append([]byte(nodeInitBanner), body...)
	if err := os.WriteFile(*configPath, out, 0o644); err != nil {
		log.Fatalf("node init: write %s: %v", *configPath, err)
	}

	// Self-check: the file just written must load cleanly through the same
	// loader --role node calls at startup, so a template bug is caught here
	// rather than at the node's first launch.
	if _, err := nodeagent.LoadConfig(*configPath); err != nil {
		_ = os.Remove(*configPath)
		log.Fatalf("node init: wrote %s but it failed to load (%v); this is a node init bug, not your input", *configPath, err)
	}

	if created {
		log.Printf("minted a new node key at %s", kp)
	} else {
		log.Printf("reused the existing node key at %s", kp)
	}
	fmt.Printf("node id:      %s\n", signer.NodeID())
	fmt.Printf("public key:   %s\n", signer.PublicKeyBase64())
	fmt.Printf("wrote config: %s\n", *configPath)
	fmt.Println()
	fmt.Println("This node holds no ssh key and needs none (design D61): enrollment is an")
	fmt.Println("operator-signed grant, minted and dropped over your own ssh/admin access,")
	fmt.Println("never the node's. Mint the grant against this node's public key:")
	fmt.Printf("  cambia harness node grant --pubkey %s --slots %d\n", signer.PublicKeyBase64(), *slots)
	fmt.Println("Drop the resulting grant file onto the coordinator's nodes directory yourself, then start this node:")
	fmt.Printf("  cambia-runnerd --role node --node-config %s\n", *configPath)
}
